MvcFriendsSite/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace MvcFriendsSite.Models
{
    public class UserModel
    {
        public int Id { get; set; }
        [Display(Name = "Name")]
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string userName { get; set; }
        [Display(Name = "Gender")]
        [StringLength(15, MinimumLength = 3)]
        [Required]
        public string gender { get; set; }

        [Display(Name = "Alias")]
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string alias { get; set; }


        [Display(Name = "Website")]
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string website { get; set; }


        [Display(Name = "Social Website")]
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string socialWebsite { get; set; }


        [Display(Name = "Email")]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string email { get; set; }

        [Display(Name = "Date Of Birth")]
        [DataType(DataType.Date)]
        public DateTime dob { get; set; }

        public ICollection<SocialModel> userToSocialFK { get; set; }



    }
}

MvcFriendsSite/Controllers/UserModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcFriendsSite.Data;
using MvcFriendsSite.Models;

namespace MvcFriendsSite.Controllers
{
    public class UserModelsController : Controller
    {
        private readonly MvcFriendsSiteContext _context;

        public UserModelsController(MvcFriendsSiteContext context)
        {
            _context = context;
        }

        // GET: UserModels
        // GET: UserModels
        public async Task<IActionResult> Index(string searchString)
        {
            var friends = from m in _context.UserModel
                          select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                friends = friends.Where(s => s.userName.Contains(searchString));
            }

            return View(await friends.ToListAsync());


        }



        // GET: UserModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userModel = await _context.UserModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userModel == null)
            {
                return NotFound();
            }

            return View(userModel);
        }

        // GET: UserModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,userName,gender,alias,website,socialWebsite,email,dob")] UserModel userModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userModel);
        }

        // GET: UserModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userModel = await _context.UserModel.FindAsync(id);
            if (userModel == null)
            {
                return NotFound();
            }
            return View(userModel);
        }

        // POST: UserModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,userName,gender,alias,website,socialWebsite,email,dob")] UserModel userModel)
        {
            if (id != userModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserModelExists(userModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userModel);
        }

        // GET: UserModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userModel = await _context.UserModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userModel == null)
            {
                return NotFound();
            }

            return View(userModel);
        }

        // POST: UserModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userModel = await _context.UserModel.FindAsync(id);
            _context.UserModel.Remove(userModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserModelExists(int id)
        {
            return _context.UserModel.Any(e => e.Id == id);
        }
    }
}

MvcFriendsSite/Views/UserModels/Create.cshtml
@model MvcFriendsSite.Models.UserModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UserModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="userName" class="control-label"></label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control" />
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="alias" class="control-label"></label>
                <input asp-for="alias" class="form-control" />
                <span asp-validation-for="alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="website" class="control-label"></label>
                <input asp-for="website" class="form-control" />
                <span asp-validation-for="website" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="socialWebsite" class="control-label"></label>
                <input asp-for="socialWebsite" class="form-control" />
                <span asp-validation-for="socialWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dob" class="control-label"></label>
                <input asp-for="dob" class="form-control" />
                <span asp-validation-for="dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcFriendsSite/Views/UserModels/Delete.cshtml
@model MvcFriendsSite.Models.UserModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.socialWebsite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.socialWebsite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dob)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcFriendsSite/Views/UserModels/Details.cshtml
@model MvcFriendsSite.Models.UserModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UserModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.socialWebsite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.socialWebsite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dob)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcFriendsSite/Views/UserModels/Edit.cshtml
@model MvcFriendsSite.Models.UserModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="userName" class="control-label"></label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control" />
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="alias" class="control-label"></label>
                <input asp-for="alias" class="form-control" />
                <span asp-validation-for="alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="website" class="control-label"></label>
                <input asp-for="website" class="form-control" />
                <span asp-validation-for="website" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="socialWebsite" class="control-label"></label>
                <input asp-for="socialWebsite" class="form-control" />
                <span asp-validation-for="socialWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dob" class="control-label"></label>
                <input asp-for="dob" class="form-control" />
                <span asp-validation-for="dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcFriendsSite/Views/UserModels/Index.cshtml
@model IEnumerable<MvcFriendsSite.Models.UserModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="UserModels" asp-action="Index">
    <p>
        User Name: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.userName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.alias)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.website)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.socialWebsite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dob)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.userName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.alias)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.website)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.socialWebsite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dob)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>