MvcFriendsSite/Models/SocialModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
namespace MvcFriendsSite.Models
{
    public class SocialModel
    {


        public int Id { get; set; }
        [Display(Name = "Name")]
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string userName { get; set; }

      


        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [Display(Name = "Email")]
        public string email { get; set; }

        [Display(Name = "Display Picture")]
        public string profilePicUrl { get; set; }

        [Display(Name = "Friend's Email")]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string friendsEmail { get; set; }


    }
}

MvcFriendsSite/Controllers/SocialModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcFriendsSite.Data;
using MvcFriendsSite.Models;

namespace MvcFriendsSite.Controllers
{
    public class SocialModelsController : Controller
    {
        private readonly MvcFriendsSiteContext _context;

        public SocialModelsController(MvcFriendsSiteContext context)
        {
            _context = context;
        }


        // GET: SocialModels
        public async Task<IActionResult> Index(string searchString)
        {

            var friends = from m in _context.SocialModel
                          select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                friends = friends.Where(s => s.userName.Contains(searchString));
            }

            return View(await friends.ToListAsync());

        }

        // GET: SocialModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var socialModel = await _context.SocialModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (socialModel == null)
            {
                return NotFound();
            }

            return View(socialModel);
        }

        // GET: SocialModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SocialModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,userName,email,profilePicUrl,friendsEmail")] SocialModel socialModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(socialModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(socialModel);
        }

        // GET: SocialModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var socialModel = await _context.SocialModel.FindAsync(id);
            if (socialModel == null)
            {
                return NotFound();
            }
            return View(socialModel);
        }

        // POST: SocialModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,userName,email,profilePicUrl,friendsEmail")] SocialModel socialModel)
        {
            if (id != socialModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(socialModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SocialModelExists(socialModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(socialModel);
        }

        // GET: SocialModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var socialModel = await _context.SocialModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (socialModel == null)
            {
                return NotFound();
            }

            return View(socialModel);
        }

        // POST: SocialModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var socialModel = await _context.SocialModel.FindAsync(id);
            _context.SocialModel.Remove(socialModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SocialModelExists(int id)
        {
            return _context.SocialModel.Any(e => e.Id == id);
        }
    }
}

MvcFriendsSite/Views/SocialModels/Create.cshtml
@model MvcFriendsSite.Models.SocialModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SocialModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="userName" class="control-label"></label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="profilePicUrl" class="control-label"></label>
                <input asp-for="profilePicUrl" class="form-control" />
                <span asp-validation-for="profilePicUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="friendsEmail" class="control-label"></label>
                <input asp-for="friendsEmail" class="form-control" />
                <span asp-validation-for="friendsEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcFriendsSite/Views/SocialModels/Delete.cshtml
@model MvcFriendsSite.Models.SocialModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SocialModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.profilePicUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.profilePicUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.friendsEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.friendsEmail)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcFriendsSite/Views/SocialModels/Details.cshtml
@model MvcFriendsSite.Models.SocialModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SocialModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.profilePicUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.profilePicUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.friendsEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.friendsEmail)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcFriendsSite/Views/SocialModels/Edit.cshtml
@model MvcFriendsSite.Models.SocialModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SocialModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="userName" class="control-label"></label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="profilePicUrl" class="control-label"></label>
                <input asp-for="profilePicUrl" class="form-control" />
                <span asp-validation-for="profilePicUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="friendsEmail" class="control-label"></label>
                <input asp-for="friendsEmail" class="form-control" />
                <span asp-validation-for="friendsEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcFriendsSite/Views/SocialModels/Index.cshtml
@model IEnumerable<MvcFriendsSite.Models.SocialModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="SocialModels" asp-action="Index">
    <p>
        User Name: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.userName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.profilePicUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.friendsEmail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.userName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.profilePicUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.friendsEmail)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>